version: '3.9'

services:
  gestionclub-api:
    build:
      context: .
    container_name: gestionclub-api
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - gestionclub-db

  gestionclub-db:
    image: mysql:8.0
    container_name: mysql_test
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=gestionclub-db
      - MYSQL_USER=gestionclub_user
      - MYSQL_PASSWORD=gestionclub-pass
    ports:
        - "3307:3306"
    volumes:
      - mysql-data-test:/var/lib/mysql

volumes:
  mysql-data-test:
    driver: local
    driver_opts:
      type: none
      device: /path/to/your/local/mysql/data
      o: bind
