# Configuracion de conexion a MySQL en AWS
spring.datasource.url=jdbc:mysql://gestionclub.cgru6wgyccsd.us-east-1.rds.amazonaws.com:3306/sumadeportes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=gestionclub_suma





















